name: deploy_pod
on:
  release:
    types: 
      - released
jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Install Cocoapods
      run: gem install cocoapods      
    - name: Deploy to Cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        set -eo pipefail
        export LIB_VERSION=${GITHUB_REF:11}
        pod lib lint --allow-warnings --no-clean
        pod trunk push --allow-warnings --no-clean
