name: publish pod
on:
  release:
    types: 
      - released
jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: anhnam00   
    - name: Install Cocoapods
      run: gem install cocoapods      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export LIB_VERSION=${GITHUB_REF:11}
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
